# Generated by Django 5.0.6 on 2024-06-16 11:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sugar', models.IntegerField(validators=[main.models.validate_ten_digits])),
                ('coffee', models.IntegerField(validators=[main.models.validate_ten_digits])),
                ('flour', models.IntegerField(validators=[main.models.validate_ten_digits])),
                ('chocolate', models.IntegerField(validators=[main.models.validate_ten_digits])),
                ('vertical', models.CharField(choices=[('HD', 'Hot Drink'), ('CD', 'Cold Drink'), ('CAKES', 'Cakes')], default='CAKES', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
