# Generated by Django 5.0.6 on 2024-06-21 14:25

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sugar', models.IntegerField(validators=[main.models.max_integer_validator])),
            ],
        ),
    ]
