# Generated by Django 5.0.6 on 2024-06-16 11:54

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[main.models.validate_ten_digits]),
        ),
    ]
