# Generated by Django 5.0.6 on 2024-06-21 16:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='milk',
            field=models.IntegerField(default=0, validators=[main.models.max_integer_validator]),
        ),
    ]
