# Generated by Django 5.0.6 on 2024-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_milk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.IntegerField(default=0)),
                ('flour', models.IntegerField(default=0)),
                ('chocolate', models.IntegerField(default=0)),
                ('milk', models.IntegerField(default=0)),
            ],
        ),
    ]
