# Generated by Django 5.0.6 on 2024-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='sugar',
            field=models.IntegerField(default=0),
        ),
    ]
