# Generated by Django 5.0.6 on 2024-06-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_warehouse_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='sales_count',
        ),
    ]
