# Generated by Django 5.0.6 on 2024-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_sales_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vertical',
            field=models.CharField(choices=[('HOT DRINK', 'Hot Drink'), ('COLD DRINK', 'Cold Drink'), ('CAKE', 'Cake'), ('ICE CREAM', 'Ice Cream')], default='HOT DRINK', max_length=10),
        ),
    ]
