# Generated by Django 5.0.6 on 2024-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
